test cache ...

diff --git a/.github/workflows/serve-ximera.yml b/.github/workflows/serve-ximera.yml
--- a/.github/workflows/serve-ximera.yml
+++ b/.github/workflows/serve-ximera.yml
@@ -50,12 +50,12 @@ jobs:
           ./xmScripts/xmlatex ghaction 
           echo "✅ Published to $XIMERA_URL$XIMERA_NAME " >> $GITHUB_STEP_SUMMARY
 
-      - name: Upload Artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: build-artifacts
-          path: .
-          retention-days: 3
+      # - name: Upload Artifacts
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: build-artifacts
+      #     path: .
+      #     retention-days: 3
 
   publish-ximera:
     name: Publish Ximera Courses
@@ -63,10 +63,37 @@ jobs:
     runs-on: ubuntu-latest
     environment: production
     steps:
-      - name: Download Artifacts
-        uses: actions/download-artifact@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
         with:
-          name: build-artifacts
+          fetch-depth: 0   # full 
+
+      # - name: Download Artifacts
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     name: build-artifacts
+
+      - name: Setup cache
+        uses: actions/cache@v4
+        id: cache-restore
+        with:
+          path: | 
+            **/*.html
+            **/*.pdf
+            **/*.svg
+            **/*.aux
+            **/*.xref
+            **/*.toc
+            !xmPictures/**
+            !.git/**
+            !.github/**
+          key: ximera-${{ github.ref_name }}-${{ github.sha }}
+
+      - name: Fail if Cache is Missing
+        if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
+        run: |
+          echo "Cache not found! Failing the job."
+          exit 1
 
       - name: Serve
         env:
